-- Fix publicação de avaliações e busca por nome/cidade via male_profiles
begin;

-- 1) Estrutura esperada de male_profiles
create table if not exists public.male_profiles (
  id bigint generated by default as identity primary key,
  display_name text not null,
  normalized_name text,
  city text,
  normalized_city text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.male_profiles
  add column if not exists display_name text,
  add column if not exists normalized_name text,
  add column if not exists city text,
  add column if not exists normalized_city text,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- 2) Normalização mínima para registros legados
update public.male_profiles
set
  normalized_name = lower(trim(display_name)),
  normalized_city = lower(trim(city))
where coalesce(normalized_name, '') = ''
   or coalesce(normalized_city, '') = '';

-- 3) Chave única para idempotência (create/reuse)
create unique index if not exists male_profiles_normalized_unique_idx
  on public.male_profiles (normalized_name, normalized_city);

-- 4) Índices de performance para busca por nome/cidade (ILIKE)
create extension if not exists pg_trgm;

create index if not exists male_profiles_normalized_name_trgm_idx
  on public.male_profiles using gin (normalized_name gin_trgm_ops);

create index if not exists male_profiles_normalized_city_trgm_idx
  on public.male_profiles using gin (normalized_city gin_trgm_ops);

create index if not exists male_profiles_is_active_idx
  on public.male_profiles (is_active);

create index if not exists avaliacoes_male_profile_publica_idx
  on public.avaliacoes (male_profile_id, publica);

-- 5) RLS: leitura pública para reputação, escrita administrativa via service_role
alter table public.male_profiles enable row level security;

-- remove políticas legadas conflitantes
DO $$
DECLARE
  p record;
BEGIN
  FOR p IN
    SELECT policyname
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'male_profiles'
  LOOP
    EXECUTE format('drop policy if exists %I on public.male_profiles', p.policyname);
  END LOOP;
END $$;

create policy "male_profiles public read active"
  on public.male_profiles
  for select
  using (is_active = true);

create policy "male_profiles service role insert"
  on public.male_profiles
  for insert
  to service_role
  with check (true);

create policy "male_profiles service role update"
  on public.male_profiles
  for update
  to service_role
  using (true)
  with check (true);

commit;
